export const cardAuto = [
	{
		id: 1,
		brand: 'Porche',
		model: '911 turbo S Cabrio',
		year: '2018',
		engine: '3,0 / 450 л.с',
		transmission: 'Автоматическая',
		fuel: 'Бензин',
		drive: 'Полный',
		photo_1: '/images/porsche_911/porsche_1.jpg',
		photo_2: '/images/porsche_911/porsche_2.jpg',
		photo_3: '/images/porsche_911/porsche_3.jpg',
		photo_4: '/images/porsche_911/porsche_4.jpg',
	},
	{
		id: 2,
		brand: 'Mercedes-Benz',
		model: 'S63e AMG 4matic',
		year: '2020',
		engine: '4.0 / 612 л.с.',
		transmission: 'Автоматическая',
		fuel: 'Бензин',
		drive: 'Полный привод',
		photo_1: '/images/Mercedes-Benz_S63/Mercedes-benz_1.jpg',
		photo_2: '/images/Mercedes-Benz_S63/Mercedes-benz_2.jpg',
		photo_3: '/images/Mercedes-Benz_S63/Mercedes-benz_3.jpg',
		photo_4: '/images/Mercedes-Benz_S63/Mercedes-benz_4.jpg',
	},
	{
		id: 3,
		brand: 'BMW',
		model: '530i xDrive M Sport Plus',
		year: '2021',
		engine: '2,0 / 249 л.с',
		transmission: 'Автоматическая',
		fuel: 'Бензин',
		drive: 'Полный привод',
		photo_1: '/images/BMW_530i/bmw_1.jpg',
		photo_2: '/images/BMW_530i/bmw_2.jpg',
		photo_3: '/images/BMW_530i/bmw_3.jpg',
		photo_4: '/images/BMW_530i/bmw_4.jpg',
	},
	{
		id: 4,
		brand: 'BMW X6',
		model: '30d 3.0 Stertonic M Sport',
		year: '2023',
		engine: '3.0 / 298 л.с.',
		transmission: 'Автоматическая',
		fuel: 'Дизель',
		drive: 'Полный привод',
		photo_1: '/images/BMW_x6/BMWx6_1.jpg',
		photo_2: '/images/BMW_x6/BMWx6_2.jpg',
		photo_3: '/images/BMW_x6/BMWx6_3.jpg',
		photo_4: '/images/BMW_x6/BMWx6_4.jpg',
	},
	{
		brand: 'Hyundai',
		model: 'Santa Fe Prestige',
		year: '2024',
		engine: '2.5 / 281 л.с.',
		transmission: 'Автоматическая',
		fuel: 'Бензин',
		drive: 'Полный привод',
		photo_1: '/images/Hyundai_santaFe/Hyundai_1.jpg',
		photo_2: '/images/Hyundai_santaFe/Hyundai_2.jpg',
		photo_3: '/images/Hyundai_santaFe/Hyundai_3.jpg',
		photo_4: '/images/Hyundai_santaFe/Hyundai_4.jpg',
	},
	{
		id: 6,
		brand: 'LiXiang',
		model: '1.5hyb 4WD AT',
		year: '2024',
		engine: '1.5 / 450 л.с.',
		transmission: 'Автоматическая',
		fuel: 'Гибрид',
		drive: 'Полный привод',
		photo_1: '/images/Lixiang/Lixiang_1.jpg',
		photo_2: '/images/Lixiang/Lixiang_2.jpg',
		photo_3: '/images/Lixiang/Lixiang_3.jpg',
		photo_4: '/images/Lixiang/Lixiang_4.jpg',
	},
	{
		id: 7,
		brand: 'Toyota Camry',
		model: '2.5 AT',
		year: '2023',
		engine: '2.5 / 206 л.с.',
		transmission: 'Автоматическая',
		fuel: 'Бензин',
		drive: 'Передний привод',
		photo_1: '/images/ToyotaCamry/ToyotaCamry_1.jpg',
		photo_2: '/images/ToyotaCamry/ToyotaCamry_2.jpg',
		photo_3: '/images/ToyotaCamry/ToyotaCamry_3.jpg',
		photo_4: '/images/ToyotaCamry/ToyotaCamry_4.jpg',
	},
]
